name: Deploy App
on: [push]
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
      - uses: actions/checkout@v2
      - id: Deploy-App
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'malthesers'
          reponame: 'vue-kanban'
          token: ${{ secrets.GITHUB_TOKEN }}
